"""Create Users table + relationship with Items

Revision ID: d17fdd6ec293
Revises: 48c025f2f15b
Create Date: 2025-12-04 15:30:20.599044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17fdd6ec293'
down_revision: Union[str, Sequence[str], None] = '48c025f2f15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'SELLER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.add_column('items', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'items', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('items', 'seller_id')
    op.drop_table('users')
    # ### end Alembic commands ###
