"""Update Item table

Revision ID: 8cefe7c290f7
Revises: 6a8284a5a4d3
Create Date: 2026-02-09 12:04:02.055864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cefe7c290f7'
down_revision: Union[str, Sequence[str], None] = '6a8284a5a4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('system_requirements', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'rating')
    op.drop_column('items', 'system_requirements')
    # ### end Alembic commands ###
